// outline-text — convert a string to an SVG <path> using a TTF/OTF font.
//
// Why: an SVG embedded as <img> on GitHub cannot load external fonts, so any
// brand text must be baked to vector outlines at build time. See
// docs/embedding-animated-svg.md.
//
// Usage:
//   node scripts/outline-text.mjs --font=assets/fonts/Anton-Regular.ttf --text="Chan Meng" --size=150
//   node scripts/outline-text.mjs --font=<ttf> --text="…" --size=34 --out=lib/presets/myText.js --key=tagline
//
// Prints (or with --out, writes a CJS module exporting) { d, width, size, text }:
//   - d:     path data, baseline at y=0, left edge at x=0 (translate to place it)
//   - width: advance width in px at the given size (for centring / fit checks)

import opentype from 'opentype.js';
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)=([\s\S]*)$/);
    return m ? [m[1], m[2]] : [a.replace(/^--/, ''), true];
  })
);

if (!args.font || args.text == null || !args.size) {
  console.error('usage: node scripts/outline-text.mjs --font=<ttf> --text="…" --size=<px> [--out=<file>] [--key=<name>] [--precision=2]');
  process.exit(2);
}

const buf = readFileSync(resolve(args.font));
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
const font = opentype.parse(ab);

const size = Number(args.size);
const precision = args.precision ? Number(args.precision) : 2;
const d = font.getPath(String(args.text), 0, 0, size).toPathData(precision);
const width = Math.round(font.getAdvanceWidth(String(args.text), size) * 100) / 100;
const entry = { d, width, size, text: String(args.text) };

if (args.out) {
  const key = args.key || 'text';
  const banner = `// AUTO-GENERATED by scripts/outline-text.mjs — do not edit by hand.\n`;
  writeFileSync(resolve(args.out), `${banner}module.exports = ${JSON.stringify({ [key]: entry }, null, 2)};\n`);
  console.error(`OK wrote ${args.out}  (${args.text} — ${width}px wide @ ${size}px)`);
} else {
  process.stdout.write(JSON.stringify(entry, null, 2) + '\n');
}
