module.exports = {
  'claude-jumping':       require('./claudeJumping'),
  'claude-speaking':      require('./claudeSpeaking'),
  'codex-jumping':        require('./codexJumping'),
  'codex-speaking':       require('./codexSpeaking'),
  'purple-robot-jumping': require('./purpleRobotJumping'),
  'chan-cover':           require('./chanCover'),
  'chan-monkey':          require('./chanMonkey'),
  'dot-loader':           require('./dotLoader'),
  'orbit-spinner':        require('./orbitSpinner'),
  'ripple-loader':        require('./rippleLoader'),
  'drift-field':          require('./driftField'),
  'spin-badge':           require('./spinBadge'),
  'star-loader':          require('./starLoader'),
  'accent-card':          require('./accentCard'),
  'hero-strip':           require('./heroStrip'),
  'gleam-banner':         require('./gleamBanner'),
  'brand-cover':          require('./brandCover'),
  'gradient-cover':       require('./gradientCover'),
  'repo-hero':            require('./repoHero'),
  'orbit-logo':           require('./orbitLogo'),
  'pulse-mono-logo':      require('./pulseMonoLogo'),
  'bounce-char':          require('./bounceChar')
};
